import type { Metadata } from "next";
import { Inter_Tight, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";


const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interTight.variable} ${instrumentSerif.variable}`}>
      <body
        className={`${interTight.variable} ${instrumentSerif.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 w-screen z-20">
          <Navbar />
        </div>
        <div className="mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
